apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-info-app
  labels:
    app: node-info
spec:
  replicas: 3  # 可以根据需要调整副本数量
  selector:
    matchLabels:
      app: node-info
  template:
    metadata:
      labels:
        app: node-info
    spec:
      containers:
      - name: node-info
        image: ccr.ccs.tencentyun.com/matrix-tools/node-info:latest  # 替换为你的镜像名称，如 registry.example.com/node-info-app:1.0
        imagePullPolicy: IfNotPresent  # 对于本地镜像使用 IfNotPresent，生产环境应使用 Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-info-service
spec:
  selector:
    app: node-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP  # 对于生产环境，可以考虑使用 LoadBalancer 或 NodePort
