apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-info-sts
  labels:
    app: node-info-sts
spec:
  serviceName: "node-info-sts"  # 必须指定对应的Headless Service
  replicas: 3  # StatefulSet会按顺序创建Pod
  selector:
    matchLabels:
      app: node-info-sts
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
  template:
    metadata:
      labels:
        app: node-info-sts
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: node-info-sts
        image: ccr.ccs.tencentyun.com/matrix-tools/node-info:latest  # 替换为你的镜像
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: web
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: web
          initialDelaySeconds: 5
          periodSeconds: 5
---
# 对应的Headless Service
apiVersion: v1
kind: Service
metadata:
  name: node-info-sts
spec:
  clusterIP: None  # Headless Service标识
  selector:
    app: node-info-sts
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
