kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      hostNetwork: true
      containers:
        - name: traefik
          image: traefik:v2.4
          args:
            - --log.level=INFO
            - --accesslog
            - --api=true
            - --api.insecure
            - --metrics.prometheus=true
            - --metrics.prometheus.addentrypointslabels
            - --metrics.prometheus.addserviceslabels
            - --entrypoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --entrypoints.tcpep.address=:8000
            - --entrypoints.web.forwardedheaders.insecure
            - --entrypoints.websecure.forwardedheaders.insecure
            - --providers.kubernetescrd
            - --providers.kubernetesingress