kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
  namespace: taas
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi