apiVersion: v1
kind: Service
metadata:
  namespace: namespace_template
  name: elasticsearch-client
  labels:
    app: elasticsearch
    role: client
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: transport
  selector:
    app: elasticsearch
    role: client

---
apiVersion: v1
kind: Service
metadata:
  namespace: elastic-system
  name: elasticsearch-client-out
spec:
  type: NodePort
  ports:
  - port: 9200
    name: client
    nodePort: 30123
  selector:
    aelasticsearch.k8s.elastic.co/cluster-name: elastic
    elasticsearch.k8s.elastic.co/statefulset-name: elastic-es-client