apiVersion: v1
kind: Service
metadata:
  namespace: namespace_template
  name: mongo-service
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
  selector:
    name: mongodb