apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra-etcd
  name: infra-etcd-cluster-client
  namespace: etcd
spec:
  ports:
  - name: infra-etcd-cluster-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
  sessionAffinity: None
  type: NodePort
