apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd-cluster
    app: etcd
  name: etcd-cluster
  namespace: etcd
spec:
  ports:
  - name: etcd-cluster-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: etcd-cluster-2380
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd
