expose:
  type: ingress
  tls:
    enabled: true
  ingress:
    hosts:
      core: registry.ianworks.me
      notary: notary.ianworks.me
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "0"

externalURL: https://registry.ianworks.me
#  type: nodePort
#  tls:
#    enabled: false
#  nodePort:
#    name: harbor
#    ports:
#      http:
#        port: 80
#        nodePort: 30120
#      https:
#        port: 443
#        nodePort: 30121
#      notary:
#        port: 4443
#        nodePort: 30122
#
#externalURL: http://192.168.101.202:30120
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "nfs-storage"
      size: 10Gi
    chartmuseum:
      storageClass: "nfs-storage"
      size: 10Gi
    jobservice:
      storageClass: "nfs-storage"
      size: 10Gi
    database:
      storageClass: "nfs-storage"
      size: 10Gi
    redis:
      storageClass: "nfs-storage"
      size: 10Gi
    trivy:
      storageClass: "nfs-storage"
      size: 5Gi