apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - name: web
      port: 3306
      targetPort: 3306
      nodePort: 30020